### ISSUE TITLE
OSError: [Errno 24] Too many open files: '/project_folder/tb/monitor-status.pickle'

### ISSUE THREAD

**Issue by stribizhev** [ufal/marian-tensorboard#1]
I ran the `tb_log_parser.py` Python script (that I modified a bit to avoid issues when reading the log file) in the background using

    nohup nice python3 /marian-dev/build/marian-tensorboard/tb_log_parser.py > /log/file/path 2>&1 &

After some 1020 occurrences of `update loop <project_name>` it throws

```
Traceback (most recent call last):
  File "/marian-dev/build/marian-tensorboard/tb_log_parser.py", line 218, in <module>
    m = JobMonitor(fldr, prefix_log)
  File "/marian-dev/build/marian-tensorboard/tb_log_parser.py", line 41, in __init__
    f = open(self.pickle_file, "rb")
OSError: [Errno 24] Too many open files: '/Engines/Gen/ENJA/tb/monitor-status.pickle'

```

The code that loads the file data is not modified:

    if os.path.exists(self.pickle_file):
        with open(self.pickle_file, "rb") as f:
            self.last_update_time, self.last_update_line, self.gpus, self.sen_last, self.avg_status, self.last_wall_time, self.gaps, self.avg_gaps, self.gaps_num = pickle.load(f)

Is there a fix for this?

**Comment by Gldkslfmsd** [comment]
Hi!
I never had this issue. I would have to see your entire modified script to suggest a fix. My guess is that you either have so many monitored jobs, so that you have many JobMonitor objects, each holding an opened file inside of self.writer causing "Too many open files". 

Or, from some reason is https://github.com/ufal/marian-tensorboard/blob/ca6c03538385fa07ca724234c13c9967a2b9fd83/tb_log_parser.py#L203 is executed many times. It should be only once for each monitored job.

Or you add a modification where you open many files and don't close them.

**Comment by stribizhev** [comment]
Thank you. I fixed the issue by moving the `with open("tb-monitored-jobs","r") as f:...` part outside the `while True` block.
